###
get http://localhost:4000/message

###
post http://localhost:4000/message/67f7734797fc6bdd8c4e1df5
Content-Type: application/json

{
    "senderId": "67f7733697fc6bdd8c4e1df4",
    "content": "I am new here"
}