###
get http://localhost:4000/message

###
post http://localhost:4000/message/67f7718322dc68138228a255
Content-Type: application/json

{
    "senderId": "67f7715d22dc68138228a252",
    "content": "Hello, how are you?"
}