###
get http://localhost:4000/user

###
get http://localhost:4000/user/chats/67f51300f0c5d341786a2866

###
post http://localhost:4000/user/
Content-Type: application/json

{
    "username": "blue",
    "email": "blue@gmail.com",
    "password": "blue"
}

###
post http://localhost:4000/user/login
Content-Type: application/json

{
    "username": "blue",
    "password": "blue"
}